# Use the official MySQL image
FROM mysql:8.4

# Only copy the shell script to the initdb directory
WORKDIR /docker-entrypoint-initdb.d
COPY database/init-db.sh .
RUN chmod +x init-db.sh

# Copy SQL files to a different directory
WORKDIR /
COPY database/*.sql /database/
